apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-accounts-db
    environment: prod
    example.com/environment.name: prod
    example.com/owner.name: backend
    example.com/tier.name: database
    holos.run/component.name: prod-bank-accounts-db
    team: backend
    tier: database
  name: accounts-db
  namespace: prod-bank-backend
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: accounts-db
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-accounts-db
    environment: prod
    example.com/environment.name: prod
    example.com/owner.name: backend
    example.com/tier.name: database
    holos.run/component.name: prod-bank-accounts-db
    team: backend
    tier: database
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-accounts-db
    environment: prod
    example.com/environment.name: prod
    example.com/owner.name: backend
    example.com/tier.name: database
    holos.run/component.name: prod-bank-accounts-db
    team: backend
    tier: database
  name: accounts-db
  namespace: prod-bank-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
      application: bank-of-holos
      argocd.argoproj.io/instance: prod-bank-accounts-db
      environment: prod
      example.com/environment.name: prod
      example.com/owner.name: backend
      example.com/tier.name: database
      holos.run/component.name: prod-bank-accounts-db
      team: backend
      tier: database
  serviceName: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
        application: bank-of-holos
        argocd.argoproj.io/instance: prod-bank-accounts-db
        environment: prod
        example.com/environment.name: prod
        example.com/owner.name: backend
        example.com/tier.name: database
        holos.run/component.name: prod-bank-accounts-db
        team: backend
        tier: database
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: environment-config
        - secretRef:
            name: accounts-db-config
        - secretRef:
            name: demo-data-config
        image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/accounts-db:v0.6.5@sha256:abb955756a82b115e0fd9c5fa1527ae1a744b398b357fd6d7a26348feccad181
        name: accounts-db
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
          subPath: postgres
        - mountPath: /docker-entrypoint-initdb.d/1-load-testdata.sh
          name: accounts-db-config
          subPath: 1-load-testdata.sh
      serviceAccount: bank-of-holos
      serviceAccountName: bank-of-holos
      volumes:
      - emptyDir: {}
        name: postgresdb
      - name: accounts-db-config
        secret:
          secretName: accounts-db-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-accounts-db
    environment: prod
    example.com/environment.name: prod
    example.com/owner.name: backend
    example.com/tier.name: database
    holos.run/component.name: prod-bank-accounts-db
    team: backend
    tier: database
  name: accounts-db-config
  namespace: prod-bank-backend
spec:
  dataFrom:
  - extract:
      key: accounts-db-config
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: prod-bank-security
  target:
    name: accounts-db-config
