apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    holos.run/component.name: istiod
  name: istiod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: deploy/clusters/workload/components/istiod
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: main
