apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    holos.run/component.name: argocd-crds
  name: argocd-crds
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: examples/environments/deploy/clusters/workload/components/argocd-crds
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
