apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    holos.run/component.name: external-secrets
  name: external-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: examples/environments/deploy/clusters/workload/components/external-secrets
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
