apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    holos.run/component.name: local-ca
  name: local-ca
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: examples/environments/deploy/clusters/workload/components/local-ca
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
