apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: prod
    example.com/environment.name: prod
    example.com/owner.name: backend
    example.com/tier.name: database
    holos.run/component.name: prod-bank-accounts-db
    team: backend
    tier: database
  name: prod-bank-accounts-db
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: prod-bank-backend
  source:
    path: examples/environments/deploy/clusters/workload/components/prod-bank-accounts-db
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
